fixed pthread_create call, Makefile changes
git-svn-id: http://source.gemini.edu/software/dhs/trunk@69 ee6ba543-07f8-4773-b02c-01d50e9d00ba

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4819,10 +4819,9 @@ if test $ac_cv_lib_socket_main = yes; then
 fi
 
 
-if test "$SYBASE" = "" ; then
-    SYBASE=/opt/sybase-12.5/OCS-12_5
-    test -d $SYBASE || SYBASE=/ocs/software/dev/packages/sybase/M0001
-fi
+SYBASE=/opt/sybase-12.5/OCS-12_5
+test -d $SYBASE || SYBASE=/ocs/software/dev/packages/sybase/M0001
+test -d $SYBASE || echo "ERROR: can't find SYBASE directory"
 
 
 if test "$TCLTK_ROOT" = "" ; then
diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -100,11 +100,10 @@ AC_CANONICAL_SYSTEM
 AC_CHECK_LIB(nsl, main, [LIBS="$LIBS -lnsl"])
 AC_CHECK_LIB(socket, main, [LIBS="$LIBS -lsocket"])
 
-dnl Sybase settings
-if test "$SYBASE" = "" ; then
-    SYBASE=/opt/sybase-12.5/OCS-12_5
-    test -d $SYBASE || SYBASE=/ocs/software/dev/packages/sybase/M0001
-fi
+dnl Sybase settings (XXX needs work)
+SYBASE=/opt/sybase-12.5/OCS-12_5
+test -d $SYBASE || SYBASE=/ocs/software/dev/packages/sybase/M0001
+test -d $SYBASE || echo "ERROR: can't find SYBASE directory"
 AC_SUBST(SYBASE)
 
 dnl Tcl settings
